#!/bin/sh

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")
red="\033[1;31m"
nocolor="\033[0m"

if ! echo "$commit_msg" | grep -qE "^[0-9]+: .+$"; then
    echo -e "${red}Error: Commit message does not match the required format '<issue number>: <commit message>'${nocolor}"
    exit 1
fi
