[tool.poetry]
name = "nobutt"
version = "0.1.0"
description = "Buttplug.io Server mock to test your applications without a physical device"
authors = ["Mihail Butvin <butvin.mihail@yandex.ru>"]
license = "MIT"
readme = "README.md"

[tool.poetry.scripts]
generate = "scripts.datamodel_generate:main"

[tool.poetry.dependencies]
python = "^3.12"
websockets = "^12.0"
pydantic = "^2.7.4"


pytest-timeout = "^2.3.1"
[tool.poetry.group.dev.dependencies]
coverage = "^7.5.3"
pytest = "^8.2.2"
mypy = { git = "https://github.com/python/mypy", branch = "master" }                                                  # We use a trunk version to have support of the new type aliases syntax. We will go back to release version as soon as all necessary features would be supported.
wemake-python-styleguide = { git = "https://github.com/wemake-services/wemake-python-styleguide", branch = "master" } # We use  a trunk version to bump flake8-commas version. Waiting for the next release.
flake8-pyproject = "^1.2.3"
autopep8 = "^2.3.0"
isort = "^5.13.2"
buttplug-py = "^0.2.0"
datamodel-code-generator = { extras = ["http"], version = "^0.25.7" }
pytest-asyncio = "^0.23.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.flake8]
format = "wemake"

max-line-length = 666 #  line length limit is useless when you have John and Cognitive Complexity limits
extend-ignore = "WPS305" #  I love f-strings :3
per-file-ignores = [
    # D: tests is a documentation, who need the documentation inside the documentation?
    # WPS442: pytest.raises requires out-of-scope variable usage
    # S101: asserts
    "tests/*: D, WPS442, S101",
]
exclude = [
    ".venv",
    "hooks",
    "*.egg",
    ".eggs",
    "dist",
    "build",
    "docs",
    ".tox",
    ".git",
    "__pycache__",
    "nobutt/spec/messages",
]
show_violation_links = true

[tool.isort]
include_trailing_comma = true
use_parentheses = true
multi_line_output = 3

[tool.autopep8]
max-line-length = 666

[tool.mypy]
strict = true
plugins = ["pydantic.mypy"]
enable_incomplete_feature = "NewGenericSyntax"
exclude = [
    ".venv",
    "hooks",
    "^.*\\.egg$",
    ".eggs",
    "dist",
    "build",
    "docs",
    ".tox",
    ".git",
    "__pycache__",
    "nobutt/spec/messages",
]


[[tool.mypy.overrides]]
module = "buttplug"
ignore_missing_imports = true

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.pytest]
norecursedirs = [
    ".venv",
    "hooks",
    "*.egg",
    ".eggs",
    "dist",
    "build",
    "docs",
    ".tox",
    ".git",
    "__pycache__",
]

[tool.coverage.run]
branch = true
source = ["nobutt"]
