function handleOk(message: Message) {}
function handlePing(message: Message) {}
function handleError(message: Message) {}
function handleDeviceAdded(message: Message) {}
function handleDeviceList(message: Message) {}
function handleDeviceRemoved(message: Message) {}
function handleServerInfo(message: Message) {}
function handleRequestServerInfo(message: Message) {}
function handleScanningFinished(message: Message) {}
function handleStartScanning(message: Message) {}
function handleStopScanning(message: Message) {}
function handleScalarCmd(message: Message) {}
function handleStopDeviceCmd(message: Message) {}
function handleStopAllDevices(message: Message) {}
