name: Check Commit Messages Starts With Issue Number

on: [push]

jobs:
    check-commit-message:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Check Commit Messages Starts With Issue Number
              run: scripts/check_commit_messages.sh
