name: Check Branch Name Starts With Issue Number

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  print_body_of_pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check Branch Name Starts With Issue Number
        run: |
          echo "Pull request body: ${{ github.event.pull_request.body }}"
          echo "Head ref: ${{ github.head_ref }}"
          scripts/check_branch_name.sh ${{ github.event.pull_request.body }} ${{ github.head_ref }}
