name: Check Commit Message

on: [push]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Check code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get pushed commits
        id: get_commits
        run: |
          commits=$(git log ${{ github.event.before }}..${{ github.event.after }} --pretty=format:'%s')
          echo "commits=$commits" >> $GITHUB_OUTPUT

      - name: Check commit messages
        run: scripts/check_commit_messages.sh
