name: Check Commit Message

on: [push]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Check code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check commit messages
        run: scripts/check_commit_messages.sh

      - name: Check branch name
        run: scripts/check_branch_name.sh "$PR_BODY" "$BRANCH_NAME"
