name: Check Commit Message

on: [push]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Check code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check commit messages
        run: scripts/check_commit_messages.sh

      - name: Check branch name
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
          BRANCH_NAME: ${{ github.head_ref }}
        run: |
            echo "PR body: $PR_BODY"
            echo "Branch name: $BRANCH_NAME"
            echo "PR body: ${{ github.event.pull_request.body }}"
            echo "Branch name: ${{ github.head_ref }}"
            scripts/check_branch_name.sh ${{ github.event.pull_request.body }} ${{ github.head_ref }}
