name: Check Commit Message

on: [push]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Check code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check commit messages
        run: scripts/check_commit_messages.sh

      - name: Check Issue Number
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
          BRANCH_NAME: ${{ github.head_ref }}
        run: |
            echo "PR_BODY: $PR_BODY"
            echo "BRANCH_NAME: $BRANCH_NAME"
